### ISSUE TITLE
Correccion

### ISSUE THREAD

**Issue by octavioramirez12** [Franpanozzo/2020_K2031_Grupo_7#3]
Solicito corrección @santiagoferreiros

**Comment by santiagoferreiros** [comment]
Grupo,

EXCELENTE TRABAJO.
Recomiendo poner todas las funciones en archivo .h
Es más fácil si van en trabajar en grupo, modularizar les permitirá una mayor comodidad.
El trabajo está muy bien, solo les remarco el tema de empezar a utilizar varios archivos para las funciones, aunque quizás tuvieron algún inconveniente al implementarlo.

Al ordenar el listado de identificadores primero pone todo lo que va con mayúscula y luego con minúscula. En ese caso debería comprar con strcasecmp

Nota: 9
